export default {
  API_REQUEST_FAILED: 'API_REQUEST_FAILED',
  API_FILE_URL_INVALID: 'API_FILE_URL_INVALID',
  API_FILE_EXECEEDS_SIZE: 'API_FILE_EXECEEDS_SIZE',
  API_CHAT_STREAM_PUSHING: 'API_CHAT_STREAM_PUSHING'
}; 